apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgresql-envs
data:
{{- range $key, $val := .Values.postgres.environment }}
  {{ $key }}: {{ tpl (print $val) $ | quote }}
{{- end }}
