apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secrets
data:
{{- range $key, $val := .Values.postgres.secrets }}
  {{ $key }}: {{ tpl (print $val) $ | b64enc }}
{{- end }}
