{{ if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-redis-data'
  labels:
    katenary.io/component: redis
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/pvc-name: redisdatadev
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 403bf1804b7c96915dbd282860506a6255f9b5c5
    katenary.io/version: 2.0.0-beta2
    helm.sh/resource-policy: keep
spec:
  resources:
    requests:
      storage: '{{ .Values.redis.persistence.capacity }}'
  accessModes:
    - ReadWriteOnce
{{- end -}}