app:
  # here secrets
  secrets:
    # ## 256 bit encryption key, 32 hex character
    AP_ENCRYPTION_KEY: 33d64cb4511a515259ee0f2dac5f413b

    # ## JWT Secret
    AP_JWT_SECRET: 6b34c24bca63731a8dd2ea3f2cf8ea56c60e4f455ef6de635aae22aff9352eb9
    # AP_PACKAGE_ARCHIVE_PATH: /usr/src/packages    
    AP_POSTGRES_PASSWORD: 9227028937a93d46404986181f64eaef37538409850d0ae8a4f14018bdebbb2b    
    # ## Random Long Password (Optional for community edition)
    # AP_API_KEY: c123c18fb91c3f353e655c5ea765c57d1c239354a8d1a567ef24630fb50524088904fd54219f6a12c9b7dfd93c07ed9262a415a00443e303d38a4de7ffa672e2

  # here environment 
  environment:
    # AP_ENGINE_EXECUTABLE_PATH: dist/packages/engine/main.js
    AP_DB_TYPE: POSTGRES
    AP_QUEUE_MODE: REDIS
    # AP_SIGN_UP_ENABLED: 'false'
    # AP_CACHE_PATH: /usr/src/cache
    # AP_ENVIRONMENT: prod
    AP_FRONTEND_URL: 'http://{{ .Release.Name }}-app.{{ .Release.Namespace }}:8080'
    AP_WEBHOOK_TIMEOUT_SECONDS: 30
    AP_TRIGGER_DEFAULT_POLL_INTERVAL: 5
    AP_POSTGRES_DATABASE: activepieces
    AP_POSTGRES_HOST: '{{ .Release.Name }}-postgres'
    AP_POSTGRES_PORT: '5432'
    AP_POSTGRES_USERNAME: postgres
    # AP_EXECUTION_MODE: UNSANDBOXED
    AP_REDIS_HOST: '{{ .Release.Name }}-redis'
    AP_REDIS_PORT: '6379'
    # AP_SANDBOX_RUN_TIME_SECONDS: 600
    # AP_TELEMETRY_ENABLED: true
    # AP_TEMPLATES_SOURCE_URL: "https://cloud.activepieces.com/api/v1/flow-templates"
  repository:
    image: 'activepieces/activepieces'
    tag: ""
  ingress:
    enabled: false
    annotations: {}
    tls: {}
    host: "activepieces.local"
    
postgres:
  secrets:
    POSTGRES_PASSWORD: '{{ .Values.app.secrets.AP_POSTGRES_PASSWORD }}'
  environment:
    POSTGRES_DB: activepieces    
    POSTGRES_USER: postgres
  persistence:
    capacity: 1Gi
    enabled: true
  repository:
    image: postgres
    tag: "14.4"
redis:
  persistence:
    capacity: 1Gi
    enabled: true
  repository:
    image: redis
    tag: "7.0.7"
